### ISSUE TITLE
API key

### ISSUE THREAD

**Issue by relic982** [crizzwald/homebridge-nexia-thermostat#1]
Thank you for creating this.

Where can we gather the API key to our Nexia Accounts?

I seem to be getting a 404 error every time it tries to gather the info from my thermostat.

**Comment by coronaflyest** [comment]
I can't wait for the Readme to be created. I have the same issue I have no idea how to get the mobile id, house id and API key.

I was able to find the house id from the thermostat going to about, but I'm still missing mobile if and API key.

**Comment by bdraco** [comment]
Try this

https://github.com/bdraco/homebridge-nexia-thermostat/blob/master/register_nexia_api
